name: darttextfinder
description: A tool to extract text strings from Flutter applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  args: ^2.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
